CREATE TABLE IF NOT EXISTS "ContactMessage" (
  "id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "firstName" VARCHAR(255) NOT NULL,
  "lastName" VARCHAR(255),
  "email" VARCHAR(255) NOT NULL,
  "phone" VARCHAR(50),
  "subject" VARCHAR(500) NOT NULL,
  "message" TEXT NOT NULL,
  "status" VARCHAR(50) NOT NULL DEFAULT 'Unread',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "ContactMessage"
  ADD COLUMN IF NOT EXISTS "firstName" VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "lastName" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "email" VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "phone" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "subject" VARCHAR(500) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "message" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "status" VARCHAR(50) NOT NULL DEFAULT 'Unread',
  ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS "ContactMessage_status_idx"
  ON "ContactMessage" ("status");

CREATE INDEX IF NOT EXISTS "ContactMessage_createdAt_idx"
  ON "ContactMessage" ("createdAt");
